# Generated by Django 4.1.5 on 2023-01-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_type',
            new_name='categoryType',
        ),
    ]
